# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 30
  timeout: 5000
  user: postgres
  password: root

development:
  <<: *default
  database: ort_dev

test:
  <<: *default
  database: ort_test

production:
  <<: *default
  database: db/production.sqlite3
